package license

// IssuerPublicKey returns the ed25519 public key the License-issuer Worker
// uses to sign JWTs (per ADR 0005).
//
// This file is regenerated by `scripts/gen-license-pubkey.go` whenever the
// issuer keypair rotates. Do NOT hand-edit -- the bytes below MUST be the
// public half of the keypair whose private half lives in Cloudflare Secrets
// under the binding name LICENSE_ISSUER_PRIVATE_KEY.
//
// Until the first real key is minted (Phase 7 Day-2), this returns 32 zero
// bytes -- which makes every Verify() fail with ErrSignature, the correct
// default for a binary built before license issuance is live.
func IssuerPublicKey() []byte {
	if override := overridePubKey; override != nil {
		return override
	}
	return issuerPubKey[:]
}

// overridePubKey is only set by tests via setIssuerPublicKey().
var overridePubKey []byte

var issuerPubKey = [32]byte{
	// Placeholder. Replace via scripts/gen-license-pubkey.go.
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
}
